---
language: ruby
sudo: false
bundler_args: --without development system_tests
before_install: rm -f Gemfile.lock
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
script: bundle exec rake test
env:
  - PUPPET_VERSION="~> 3.3.0"
  - PUPPET_VERSION="~> 3.4.0"
  - PUPPET_VERSION="~> 3.5.0"
  - PUPPET_VERSION="~> 3.6.0"
  - PUPPET_VERSION="~> 3.7.0" FUTURE_PARSER=yes
  - PUPPET_VERSION="~> 3.8.0" FUTURE_PARSER=yes
  - PUPPET_VERSION="~> 4.1.0"
  - PUPPET_VERSION="~> 4.2.0"
matrix:
  exclude:
  - rvm: 2.1
    env: PUPPET_VERSION="~> 3.3.0"
  - rvm: 2.1
    env: PUPPET_VERSION="~> 3.4.0"
